import React, { useState, useCallback, useEffect, useRef, useLayoutEffect } from 'react';
import { createPortal } from 'react-dom';
import PredictionChart from '../components/PredictionChart';
import PredictionCard from '../components/PredictionCard';
import PredictionInsights from '../components/PredictionInsights';
import { AlertCircle, RotateCcw, History, Search, ChevronDown, X } from 'lucide-react';

const API_BASE = 'http://localhost:5000/api';

const COUNTRIES = [
  "United Kingdom", "France", "Australia", "Netherlands", "Germany", "Norway",
  "EIRE", "Switzerland", "Spain", "Poland", "Portugal", "Italy", "Belgium",
  "Lithuania", "Japan", "Iceland", "Channel Islands", "Denmark", "Cyprus",
  "Sweden", "Finland", "Austria", "Greece", "Singapore", "Lebanon",
  "United Arab Emirates", "Israel", "Saudi Arabia", "Czech Republic", "Canada",
  "Unspecified", "Brazil", "USA", "European Community", "Bahrain", "Malta", "RSA"
];

// ─── YOUR FULL PRODUCT LIST ───
const ALL_PRODUCTS = [
  "BLUE SQUARE COMPACT MIRROR",
  "CHILDRENS CUTLERY DOLLY GIRL",
  "CHILDRENS CUTLERY SPACEBOY",
  "TUMBLER NEW ENGLAND",
  "BOTANICAL LILY GIFT WRAP",
  "BAROQUE BUTTERFLY EARRINGS BLACK",
  "YELLOW/ORANGE FLOWER DESIGN PLATE",
  "SWEETHEART KEY CABINET",
  "CHARLOTTE BAG VINTAGE ALPHABET",
  "JUMBO BAG ALPHABET",
  "LUNCH BAG ALPHABET DESIGN",
  "JUMBO BAG APPLES",
  "LUNCH BAG APPLE DESIGN",
  "CHARLOTTE BAG APPLES DESIGN",
  "CHARLOTTE BAG ALPHABET  DESIGN",
  "KIDS CUTLERY SPACEBOY",
  "KIDS CUTLERY DOLLY GIRL",
  "LUNCH BAG VINTAGE LEAF DESIGN",
  "S/2 BEACH HUT TREASURE CHESTS",
  "PINK FEATHERS CURTAIN",
  "PADS TO MATCH ALL CUSHIONS",
  "SQUARECUSHION COVER PINK UNION JACK",
  "3 BIRDS CANVAS SCREEN",
  "LARGE DECO JEWELLERY STAND",
  "PASTEL BLUE PHOTO ALBUM",
  "HEART BEADED TRELLIS DECORATION",
  "GEMSTONE CHANDELIER T-LIGHT HOLDER",
  "16 PIECE CUTLERY SET PANTRY DESIGN",
  "BEADED CHANDELIER T-LIGHT HOLDER",
  "CHILDRENS TOY COOKING UTENSIL SET",
  "BLACK GLASS/SHELL/PEARL NECKLACE",
  "SMALL DECO JEWELLERY STAND",
  "ALUMINIUM STAMPED HEART",
  "DOUBLE CERAMIC PARLOUR HOOK",
  "ZINC SWEETHEART WIRE LETTER RACK",
  "FLOWER GLASS GARLAND NECKL.36\"BLUE",
  "PARLOUR CERAMIC WALL HOOK",
  "GEORGIAN TRINKET BOX",
  "ORANGE/FUSCHIA STONES NECKLACE",
  "COTE D'AZURE NECKLACE",
  "TRIPLE HOOK ANTIQUE IVORY ROSE",
  "VINTAGE EMBOSSED HEART",
  "GOLD WINE GOBLET",
  "GOLD APERITIF GLASS",
  "IVORY CHANDELIER T-LIGHT HOLDER",
  "FLOWERS CHANDELIER T-LIGHT HOLDER",
  "ROSE DU SUD CUSHION COVER",
  "TRIPLE WIRE HOOK IVORY HEART",
  "TRIPLE WIRE HOOK PINK HEART",
  "SMALL ZINC HEART WALL ORGANISER",
  "SMALL IVORY HEART WALL ORGANISER",
  "MARIE ANTOIENETT TRINKET BOX GOLD",
  "IVORY SWEETHEART WIRE LETTER RACK",
  "LARGE ZINC HEART WALL ORGANISER",
  "LARGE IVORY HEART WALL ORGANISER",
  "60 GOLD AND SILVER FAIRY CAKE CASES",
  "SINGLE ANTIQUE ROSE HOOK IVORY",
  "MINIATURE ANTIQUE ROSE HOOK IVORY",
  "ZINC T-LIGHT HOLDER STARS SMALL",
  "IVORY WIRE KITCHEN ORGANISER",
  "IVORY WIRE SWEETHEART LETTER TRAY",
  "SINGLE WIRE HOOK PINK HEART",
  "SINGLE WIRE HOOK IVORY HEART",
  "IVORY SWEETHEART SOAP DISH",
  "ZINC T-LIGHT HOLDER STAR LARGE",
  "PINK BUTTERFLY CUSHION COVER",
  "BAROQUE BUTTERFLY EARRINGS RED",
  "ZINC WIRE SWEETHEART LETTER TRAY",
  "LILAC VOTIVE CANDLE",
  "TEATIME GEL PENS ASST",
  "EDWARDIAN PHOTO FRAME",
  "MAXWELL 2 TONE BLUE 60 PAGE PHOTO A",
  "MISTLETOE HEART WREATH CREAM",
  "HANGING ENGRAVED METAL HEART",
  "BLUE TABLE RUN FLOWER",
  "BLUE STRIPES SHOULDER BAG",
  "BLUE CHECK BAG W HANDLE 34X20CM",
  "LASER CUT MULTI STRAND NECKLACE",
  "REGENCY SUGAR TONGS",
  "DOORMAT KEEP CALM AND COME IN",
  "DOORMAT VINTAGE LEAVES DESIGN",
  "REGENCY TEA STRAINER",
  "FLAG OF ST GEORGE CAR FLAG",
  "HAYNES CAMPER SHOULDER BAG",
  "SMALL ZINC/GLASS CANDLEHOLDER",
  "GOLD FLOWER CUSHION COVER",
  "SET OF 10 LANTERNS FAIRY LIGHT STAR",
  "PAPER LANTERN 7 POINT SNOW STAR",
  "PAPER LANTERN 9 POINT SNOW STAR",
  "CINDERELLA CHANDELIER",
  "BLING KEY RING STAND",
  "MULTICOLOUR POLKADOT PLATE",
  "MISTLETOE HEART WREATH GREEN",
  "WHITE 3 FRAME BIRDS AND TREE",
  "WRAP SUMMER ROSE DESIGN",
  "FRENCH PAISLEY CUSHION COVER",
  "REGENCY TEA SPOON",
  "REGENCY CAKE FORK",
  "REGENCY CAKE SLICE",
  "ANTIQUE IVORY WIRE BOWL SMALL",
  "MINITURE ANTIQUE ROSE HOOK IVORY",
  "PINK FLOCK PHOTO FRAME",
  "ZINC WIRE KITCHEN ORGANISER",
  "FOOD COVER WITH BEADS SET 2",
  "SPOTTY BUNTING",
  "EDWARDIAN HEART PHOTO FRAME",
  "ZINC SWEETHEART SOAP DISH",
  "CRYSTAL STUD EARRINGS CLEAR DISPLAY",
  "PAPER LANTERN 9 POINT HOLLY STAR 40",
  "PAPER LANTERN 5 POINT STAR MOON 30",
  "PAPER LANTERN 6 POINT SNOW STAR",
  "BUNTING , SPOTTY",
  "POLYESTER FILLER PAD 60x40cm",
  "BLUE DISCO HANDBAG",
  "JUMBO BAG VINTAGE LEAF",
  "JUMBO BAG PEARS",
  "JUMBO BAG DOILEY PATTERNS",
  "LUNCH BAG DOILEY PATTERN",
  "MARIE ANTOINETTE TRINKET BOX GOLD",
  "MARIE ANTOINETTE TRINKET BOX SILVER",
  "PAPER LANTERN 9 POINT HOLLY STAR L",
  "PAPER LANTERN 9 POINT DELUXE STAR",
  "PAPER LANTERN 5 POINT SEQUIN STAR",
  "PAPER LANTERN 9 POINT HOLLY STAR S",
  "PAPER LANTERN 9 POINT HOLLY STAR 23",
  "PAPER LANTERN 5 POINT STUDDED STAR",
  "FOOD COVER WITH BEADS , SET 2 SIZES",
  "FLOWER GARLAND NECKLACE RED",
  "CRYSTAL CZECH CROSS PHONE CHARM",
  "FOLDING BUTTERFLY MIRROR IVORY",
  "FOLDING BUTTERFLY MIRROR HOT PINK",
  "BUNDLE OF 3 SCHOOL EXERCISE BOOKS",
  "BUNDLE OF 3 RETRO NOTE BOOKS",
  "BUNDLE OF 3 ALPHABET EXERCISE BOOKS",
  "BUNDLE OF 3 RETRO EXERCISE BOOKS",
  "REGENCY MILK JUG PINK",
  "REGENCY SUGAR BOWL GREEN",
  "REGENCY TEAPOT ROSES",
  "REGENCY TEA PLATE PINK",
  "REGENCY TEA PLATE GREEN",
  "REGENCY TEA PLATE ROSES",
  "GREEN METAL BOX ARMY SUPPLIES",
  "RABBIT NIGHT LIGHT",
  "FOLDING BUTTERFLY MIRROR RED",
  "PARISIENNE JEWELLERY DRAWER",
  "PETIT TRAY CHIC",
  "ZINC HERB GARDEN CONTAINER",
  "LE GRAND TRAY CHIC SET",
  "SET OF 10 LED DOLLY LIGHTS",
  "RED METAL BOX TOP SECRET",
  "GREEN METAL BOX TOP SECRET",
  "PARISIENNE KEY CABINET",
  "SILVER BELLS TABLE DECORATION",
  "SILVER HEARTS TABLE DECORATION",
  "VINTAGE ENGRAVED HEART",
  "SET 6 PAPER TABLE LANTERN HEARTS",
  "FLOWERS HANDBAG blue and orange",
  "SMALL PARISIENNE HEART PHOTO FRAME",
  "FOLDING MIRROR HOT PINK",
  "LED TEA LIGHTS",
  "BELL HEART DECORATION",
  "ALUMINIUM HEART",
  "CRYSTAL CHANDELIER T-LIGHT HOLDER",
  "PARISIENNE CURIO CABINET",
  "PARISIENNE SEWING BOX",
  "TOADSTOOL BEDSIDE LIGHT",
  "SMALL CERAMIC TOP STORAGE JAR",
  "IVORY PANTRY HANGING LAMP",
  "CLASSIC SUGAR DISPENSER",
  "MISELTOE HEART WREATH WHITE",
  "MISELTOE HEART WREATH",
  "CLASSIC GLASS SWEET JAR",
  "LARGE CERAMIC TOP STORAGE JAR",
  "LARGE JEWELLERY STAND",
  "SMALL JEWELLERY STAND",
  "SILVER STARS TABLE DECORATION",
  "GLASS BON BON JAR",
  "WHITE WIRE PLANT POT HOLDER",
  "CLASSIC GLASS COOKIE JAR",
  "CLASSIC CAFE SUGAR DISPENSER",
  "ZINC HEART FLOWER T-LIGHT HOLDER",
  "JINGLE BELL HEART DECORATION",
  "ZINC HEARTS PLANT POT HOLDER",
  "WHITE HEARTS WIRE PLANT POT HOLDER",
  "ZINC  HEART T-LIGHT HOLDER",
  "METAL HERB GERDEN CONTAINER",
  "ZINC PLANT POT HOLDER",
  "FOLDING MIRROR IVORY",
  "FOLDING MIRROR RED",
  "PEARL & SHELL 42\"NECKL. IVORY",
  "SET 6 PAPER TABLE LANTERN STARS",
  "GARDENERS KNEELING PAD KEEP CALM",
  "GARDENERS KNEELING PAD CUP OF TEA",
  "KNEELING MAT HOUSEWORK  DESIGN",
  "ENGLISH ROSE SCENTED HANGING HEART",
  "VINTAGE GLASS T-LIGHT HOLDER",
  "LARGE ANTIQUE WHITE PHOTO FRAME",
  "ANTIQUE SILVER BAUBLE LAMP",
  "FRENCH CARRIAGE LANTERN",
  "ZINC  STAR T-LIGHT HOLDER",
  "FUNKY FLOWER PICNIC BAG FOR 4",
  "SET 10 NIGHT OWL LIGHTS",
  "HEART SHAPED HOLLY WREATH",
  "LILY BROOCH WHITE/SILVER COLOUR",
  "BLUE DELPHINIUM ARTIFICIAL FLOWER",
  "IVORY CAFE HANGING LAMP",
  "RED PEONY CUSHION COVER",
  "GREEN PEONY CUSHION COVER",
  "SILVER FLOWR PINK SHELL NECKLACE",
  "ZINC T-LIGHT HOLDER STARS LARGE",
  "16 PC CUTLERY SET PANTRY DESIGN",
  "CAPIZ CHANDELIER",
  "SILVER BLACK ORBIT DROP EARRINGS",
  "FILIGREE HEART BIRD WHITE",
  "FILIGREE HEART BUTTERFLY WHITE",
  "ZINC STAR T-LIGHT HOLDER",
  "DECORATION SITTING BUNNY",
  "CHERRY BLOSSOM PURSE",
  "FILIGREE HEART DAISY WHITE",
  "SET 4 VALENTINE DECOUPAGE HEART BOX",
  "REINDEER HEART DECORATION SILVER",
  "CHAMPAGNE TRAY BLANK CARD",
  "JINGLE BELL HEART ANTIQUE GOLD",
  "JINGLE BELL HEART ANTIQUE SILVER",
  "WHITE ROCKING HORSE HAND PAINTED",
  "STAR WREATH DECORATION WITH BELL",
  "HEART WREATH DECORATION WITH BELL",
  "LAUREL STAR ANTIQUE SILVER",
  "CHERUB HEART DECORATION GOLD",
  "RED ROCKING HORSE HAND PAINTED",
  "LAUREL HEART ANTIQUE GOLD",
  "LAUREL HEART ANTIQUE SILVER",
  "CHERUB HEART DECORATION SILVER",
  "SET 2 TEA TOWELS I LOVE LONDON",
  "SET OF 3 HANGING OWLS OLLIE BEAK",
  "SET OF 3 WOODEN HEART DECORATIONS",
  "PAPER LANTERN 5 POINT STAR MOON",
  "SET OF 60 I LOVE LONDON CAKE CASES",
  "SET OF 2 CERAMIC PAINTED HEARTS",
  "SET OF 60 PANTRY DESIGN CAKE CASES",
  "SET OF 36 DOILIES PANTRY DESIGN",
  "SET OF 60 VINTAGE LEAF CAKE CASES",
  "HEART T-LIGHT HOLDER WILLIE WINKIE",
  "STAR T-LIGHT HOLDER WILLIE WINKIE",
  "BAROQUE BUTTERFLY EARRINGS MONTANA",
  "WRAP GINGHAM ROSE",
  "MIRRORED WALL ART SNOWFLAKES",
  "POP ART PUSH DOWN RUBBER",
  "WHITE FRANGIPANI HAIR CLIP",
  "SET OF 4 KNICK KNACK TINS DOILEY",
  "SET OF 4 KNICK KNACK TINS LONDON",
  "BLUE FELT HANGING HEART WITH FLOWER",
  "VINTAGE KEEPSAKE BOX PINK FLOWER",
  "SET OF TEA COFFEE SUGAR TINS PANTRY",
  "PINK FLOCK SUEDE CUSHION COVER",
  "SET OF 3 REGENCY CAKE TINS",
  "SET OF 4 KNICK KNACK TINS POPPIES",
  "DOILEY STORAGE TIN",
  "STORAGE TIN VINTAGE LEAF",
  "TREASURE TIN GYMKHANA DESIGN",
  "TREASURE TIN BUFFALO BILL",
  "BISCUIT TIN 50'S CHRISTMAS",
  "ROUND STORAGE TIN VINTAGE LEAF",
  "SET OF 4 KNICK KNACK TINS LEAVES",
  "36 DOILIES VINTAGE CHRISTMAS",
  "FOLKART CHRISTMAS TREE T-LIGHT HOLD",
  "BUBBLEGUM RING ASSORTED",
  "SMALL WHITE HEART OF WICKER",
  "DOILEY BISCUIT TIN",
  "REINDEER HEART DECORATION GOLD",
  "SET OF 3 WOODEN SLEIGH DECORATIONS",
  "SET OF 3 WOODEN TREE DECORATIONS",
  "SET OF 3 WOODEN STOCKING DECORATION",
  "DANISH ROSE UMBRELLA STAND",
  "PICNIC BASKET WICKER 60 PIECES",
  "SET OF 2 CERAMIC CHRISTMAS TREES",
  "SET OF 2 CERAMIC CHRISTMAS REINDEER",
  "VINTAGE RED ENAMEL TRIM JUG",
  "LARGE WHITE HEART OF WICKER",
  "POPCORN HOLDER",
  "DOLPHIN WINDMILL",
  "BLUE VINTAGE SPOT BEAKER",
  "EGG FRYING PAN RED",
  "PINK VINTAGE SPOT BEAKER",
  "GREEN VINTAGE SPOT BEAKER",
  "JUMBO BAG VINTAGE CHRISTMAS",
  "SMALL POP BOX FUNKY MONKEY",
  "GLASS BEAD HOOP NECKLACE BLACK",
  "FLOWER GLASS GARLAND NECKL.36\"GREEN",
  "ANTIQUE MID BLUE FLOWER EARRINGS",
  "CHRISTMAS TABLE CANDLE SILVER SPIKE",
  "EGG FRYING PAN IVORY",
  "EGG FRYING PAN BLUE",
  "EGG FRYING PAN PINK",
  "EGG FRYING PAN MINT",
  "SPACE BOY CHILDRENS CUP",
  "DOLLY GIRL CHILDRENS CUP",
  "DOLLY GIRL CHILDRENS BOWL",
  "SPACEBOY CHILDRENS BOWL",
  "RED VINTAGE SPOT BEAKER",
  "VINTAGE  2 METER FOLDING RULER",
  "BISCUIT TIN VINTAGE LEAF",
  "CANNISTER VINTAGE LEAF DESIGN",
  "VINTAGE RED ENAMEL TRIM MUG",
  "VINTAGE RED ENAMEL TRIM PLATE",
  "VINTAGE RED TRIM ENAMEL BOWL",
  "VINTAGE DONKEY TAIL GAME",
  "BISCUIT TIN VINTAGE CHRISTMAS",
  "GLASS APOTHECARY BOTTLE PERFUME",
  "GLASS APOTHECARY BOTTLE ELIXIR",
  "DRAWER KNOB CERAMIC IVORY",
  "CROCHET DOG KEYRING",
  "GLASS  SONGBIRD STORAGE JAR",
  "DRAWER KNOB CRACKLE GLAZE IVORY",
  "DRAWER KNOB CRACKLE GLAZE BLUE",
  "DRAWER KNOB CRACKLE GLAZE PINK",
  "DRAWER KNOB CRACKLE GLAZE GREEN",
  "DRAWER KNOB CERAMIC RED",
  "DRAWER KNOB CERAMIC BLACK",
  "GLASS APOTHECARY BOTTLE TONIC",
  "DONKEY TAIL GAME",
  "TRANSPARENT ACRYLIC TAPE DISPENSER",
  " TOADSTOOL BEDSIDE LIGHT",
  "JUMBO BAG 50'S CHRISTMAS",
  "DOORKNOB CRACKED GLAZE IVORY",
  "DOORKNOB CRACKED GLAZE BLUE",
  "SMALL BONNE JAM JAR  T-LIGHT HOLDER",
  "GLASS TWIST BON BON JAR",
  "DRAWER KNOB VINTAGE GLASS STAR",
  "PACK OF 6 LARGE FRUIT STRAWS",
  "SPACEBOY CHILDRENS CUP",
  "CORDIAL GLASS JUG",
  "COCKTAIL SWORDS 50 PIECES",
  "PARTY CHARMS 50 PIECES",
  "PACK OF 6 SMALL FRUIT STRAWS",
  "PACK OF 6 COCKTAIL PARASOL STRAWS",
  "18PC WOODEN CUTLERY SET DISPOSABLE",
  "6PC WOOD PLATE SET DISPOSABLE",
  "T-LIGHT HOLDER SILVER HEART HANDLE",
  "GLASS BONNE JAM JAR",
  "RIDGED BONNE JAM JAR T-LIGHT HOLDER",
  "CLASSICAL ROSE TABLE LAMP",
  "SMALL APOTHECARY MEASURING JAR",
  "TREE T-LIGHT HOLDER WILLIE WINKIE",
  "T-LIGHT HOLDER SILVER PETIT FOUR",
  "WRAP VINTAGE LEAF DESIGN",
  "PANTRY MAGNETIC  SHOPPING LIST",
  "DRAWER KNOB VINTAGE GLASS HEXAGON",
  "LARGE BONNE JAM JAR  T-LIGHT HOLDER",
  "CHRISTMAS TREE HANGING SILVER",
  "CHRISTMAS TREE HANGING GOLD",
  "SKETCHBOOK MAGNETIC SHOPPING LIST",
  "RETRO LEAVES MAGNETIC NOTEPAD",
  "SET OF 4 SANTA PLACE SETTINGS",
  "WHITE WICKER STAR",
  "IVORY REFECTORY CLOCK",
  "RED REFECTORY CLOCK",
  "MINT DINER WALL CLOCK",
  "PINK DINER WALL CLOCK",
  "RETO LEAVES MAGNETIC SHOPPING LIST",
  "CANDLE HOLDER SILVER MADELINE",
  "VEGETABLE MAGNETIC  SHOPPING LIST",
  "CHRISTMAS TABLE SILVER CANDLE SPIKE",
  "DIAMANTE NECKLACE PURPLE",
  "BLUE REFECTORY CLOCK",
  "APOTHECARY MEASURING JAR",
  "LARGE APOTHECARY MEASURING JAR",
  "DOORKNOB CRACKED GLAZE PINK",
  "DOORKNOB CRACKED GLAZE GREEN",
  "DRAWER KNOB VINTAGE GLASS BALL",
  "GLASS SONGBIRD STORAGE JAR",
  "TRAVEL CARD WALLET VINTAGE LEAF",
  "PINK EASTER HENS+FLOWER",
  "VIP PASSPORT COVER",
  "GARAGE KEY FOB",
  "BELL HEART ANTIQUE GOLD",
  "LEAVES MAGNETIC  SHOPPING LIST",
  "BOX OF 6 MINI VINTAGE CRACKERS",
  "BAROQUE BUTTERFLY EARRINGS CRYSTAL",
  "ROUND BLUE CLOCK WITH SUCKER",
  "ROUND PURPLE CLOCK WITH SUCKER",
  "FLOWER PURPLE CLOCK WITH SUCKER",
  "FLOWER BLUE CLOCK WITH SUCKER",
  "SET OF 4 KNICK KNACK TINS LEAF",
  "GIANT 50'S CHRISTMAS CRACKER",
  "DOORMAT VINTAGE LEAF",
  "PACKING CHARGE",
  "VINTAGE LEAF MAGNETIC NOTEPAD",
  "GREEN CRYSTAL DROP EARRINGS",
  "TRAVEL CARD WALLET DOTCOMGIFTSHOP",
  "BOX OF 6 MINI 50'S CRACKERS",
  "COPPER AND BRASS BAG CHARM",
  "IVORY GOLD METAL BAG CHARM",
  "WHITE WITH METAL BAG CHARM",
  "GREEN WITH METAL BAG CHARM",
  "RED PEONY TABLE CLOCK",
  "LILAC FEATHERS CURTAIN",
  "VINTAGE BEAD PINK JEWEL BOX",
  "T-LIGHT HOLDER SILVER SAUCER",
  "VINTAGE CHRISTMAS BUNTING",
  "SET OF 6 TEA TIME BAKING CASES",
  "SET OF 6 SNACK LOAF BAKING CASES",
  "SET OF 12 FAIRY CAKE BAKING CASES",
  "SET OF 12 MINI LOAF BAKING CASES",
  "SET 40 HEART SHAPE PETIT FOUR CASES",
  "ANTIQUE SILVER BOOK MARK WITH BEADS",
  "BROWN VINTAGE VICTORIAN EARRINGS",
  "PSYCHEDELIC METAL SIGN CALENDAR",
  "ROUND ARTICULATED PINK CLOCK W/SUCK",
  "PINK/BLUE STRING CURTAIN",
  "ENAMEL JUG PANTRY",
  "ENAMEL BOWL PANTRY",
  "ENAMEL MUG PANTRY",
  "VINTAGE CHRISTMAS STOCKING",
  "VINTAGE CHRISTMAS TABLECLOTH",
  "AMBER BERTIE MOBILE PHONE CHARM",
  "PINK BEADS+HAND PHONE CHARM",
  "PACK OF SIX LED TEA LIGHTS",
  "VINTAGE CHRISTMAS GIFT SACK",
  "SPOTTED WHITE NATURAL SEED NECKLACE",
  "ORANGE PENDANT TRIPLE SHELL NECKLAC",
  "WRAP ALPHABET POSTER",
  "LAUREL STAR ANTIQUE GOLD",
  "BLUE/YELLOW CERAMIC CANDLE HOLDER",
  "GREEN/BLUE CERAMIC CANDLE HOLDER",
  "AMBER 3 BEAD DROP EARRINGS",
  "PURPLE DRESS JEWELLERY STAND",
  "WRAP BIRD GARDEN",
  "WRAP PAISLEY PARK",
  "THE KING GIFT BAG 25x24x12cm",
  "BLUE MONTE CARLO HANDBAG",
  "CUTE RABBIT CEATURE SCREEN",
  "CUTE BIRD CEATURE SCREEN",
  "WRAP RED DOILEY",
  "WRAP FLOWER SHOP",
  "WRAP MAGIC FOREST",
  "WHITE STONE/CRYSTAL EARRINGS",
  "BIRD ON BRANCH CANVAS SCREEN",
  "WRAP 50'S  CHRISTMAS",
  "SPACEBOY BEAKER",
  " DOLLY GIRL BEAKER",
  "I LOVE LONDON BEAKER",
  "DOORKNOB CERAMIC IVORY",
  "ORIENTAL RED CUSHION COVER",
  "LIGHT PINK FLOCK GLASS CANDLEHOLDER",
  "MONEY BOX FIRST AID DESIGN",
  "VINTAGE CHRISTMAS CAKE FRILL",
  "MISELTOE HEART WREATH CREAM",
  "VINTAGE BEAD PINK JEWEL STAND",
  "SET 8 CANDLES VINTAGE DOILEY",
  "SET OF 12 T-LIGHTS VINTAGE DOILEY",
  "VINTAGE CHRISTMAS PAPER GIFT BAG",
  "GIFT BAG LARGE VINTAGE CHRISTMAS",
  "6 GIFT TAGS VINTAGE CHRISTMAS",
  "6 GIFT TAGS 50'S CHRISTMAS",
  "RED SPOT PAPER GIFT BAG",
  "Dotcomgiftshop Gift Voucher Â£100.00",
  " RED SPOT GIFT BAG LARGE",
  "SET OF 12 FORK CANDLES",
  "BLUE PAINTED KASHMIRI CHAIR",
  "ROLL WRAP VINTAGE CHRISTMAS",
  "ROLL WRAP VINTAGE SPOT",
  "GIFT BAG LARGE SPOT",
  "ROLL WRAP 50'S RED CHRISTMAS",
  "ROLL WRAP 50'S CHRISTMAS",
  "STORAGE TIN VINTAGE DOILEY",
  "JUMBO BAG VINTAGE DOILEY",
  "LUNCH BAG VINTAGE DOILEY",
  "ADULT APRON APPLE DELIGHT",
  "WRAP  VINTAGE DOILEY",
  "SET OF 4 KNICK KNACK TINS DOILY",
  "RUSTIC STRAWBERRY JAMPOT LARGE",
  "PURPLE ENAMEL+GLASS HAIR COMB",
  "JUMBO BAG VINTAGE DOILY",
  "LUNCH BAG VINTAGE DOILY",
  "SET 8 CANDLES VINTAGE DOILY",
  "STORAGE TIN VINTAGE DOILY",
  "IVORY WICKER HEART LARGE",
  "DECORATIVE WICKER HEART LARGE",
  "ASSORTED COLOURED CIRCLE MOBILE",
  "DECORATIVE WICKER HEART MEDIUM",
  "IVORY WICKER HEART SMALL",
  "IVORY WICKER HEART MEDIUM",
  "SET 6 SCHOOL MILK BOTTLES IN CRATE",
  "WRAP  VINTAGE DOILY",
  "SET OF 4 KNICK KNACK TINS  DOILEY",
  "DECORATIVE WICKER HEART SMALL",
  "HANGING CLEAR MINI BOTTLE",
  "SET OF 12 T-LIGHTS VINTAGE DOILY",
  "HANGING MINI COLOURED BOTTLES",
  "RUSTIC STRAWBERRY JAMPOT SMALL",
  "PINK ACRYLIC JEWEL SNOWFLAKE",
  "ACRYLIC JEWEL ANGEL,PINK",
  "WRAP RED VINTAGE DOILY",
  "CRACKED GLAZE NECKLACE BROWN",
  "RUSTIC STRAWBERRY JAM POT SMALL",
  "PINK/WHITE CHRISTMAS TREE 30CM",
  "ACRYLIC JEWEL ICICLE, BLUE",
  "RUSTIC STRAWBERRY JAM POT LARGE",
  "VINTAGE CHRISTMAS GIFT BAG LARGE",
  "HOT WATER BOTTLE SEX BOMB",
  "HOT STUFF HOT WATER BOTTLE",
  "50'S CHRISTMAS PAPER GIFT BAG",
  "LOVE HOT WATER BOTTLE",
  "3 BLACK CATS W HEARTS BLANK CARD",
  "HAPPY BIRTHDAY CARD STRIPEY TEDDY",
  "HOT WATER BOTTLE KEEP CALM",
  "DIAMANTE NECKLACE GREEN",
  " 50'S CHRISTMAS GIFT BAG LARGE",
  "CORDIAL JUG",
  "ICE CREAM BUBBLES",
  "HAND WARMER RED LOVE HEART",
  "NATURAL HANGING QUILTED HEARTS",
  "HANGING QUILTED PATCHWORK APPLES",
  "HAPPY BIRTHDAY CARD TEDDY/CAKE",
  "3 DRAWER ANTIQUE WHITE WOOD CABINET",
  "FLOWER FAIRY 5 DRAWER LINERS",
  "ELEPHANT BIRTHDAY CARD",
  "HANGING JAM JAR T-LIGHT HOLDERS",
  "FILIGREE DIAMANTE CHAIN",
  "CRUK Commission",
  "PARTY CONES CANDY DECORATION",
  "PRETTY HANGING QUILTED HEARTS",
  "SWEETHEART 3 TIER CAKE STAND",
  "PACK OF 12 VINTAGE CHRISTMAS TISSUE",
  "PACK OF 12 50'S CHRISTMAS TISSUES",
  "PACK OF 12 PAISLEY PARK TISSUES",
  "FAIRY TALE COTTAGE NIGHT LIGHT",
  "SET 10 CARDS PERFECT POST 17090",
  "SET 10 CARD CHRISTMAS WELCOME 17112",
  "SET 10 CARDS XMAS CHOIR 17068",
  "MINT DINER CLOCK",
  "BUTTERFLY CUSHION COVER",
  "BELLE JARDINIERE CUSHION COVER",
  "POSTE FRANCE CUSHION COVER",
  "SET OF 2 TRAYS HOME SWEET HOME",
  "HOME SWEET HOME CUSHION COVER",
  "STOOL HOME SWEET HOME",
  "FOOT STOOL HOME SWEET HOME",
  "PACK OF 12 DOLLY GIRL TISSUES",
  "HOME SWEET HOME HANGING HEART",
  " TRELLIS COAT RACK",
  "HANGING HEART BONHEUR",
  "LA JARDIN BOTANIQUE CUSHION COVER",
  "STORAGE TIN HOME SWEET HOME",
  "ZINC BOX SIGN HOME",
  "GINGHAM RECIPE BOOK BOX",
  "HOME SWEET HOME BLACKBOARD",
  "HOME SWEET HOME KEY HOLDER",
  "HOME SWEET HOME 2 DRAWER CABINET",
  "PACK OF 12 RED APPLE TISSUES",
  "PACK OF 12 VINTAGE LEAF TISSUES",
  "PACK OF 12 VINTAGE DOILY TISSUES",
  "HOME SWEEET HOME 3 PEG HANGER",
  "LETTER HOLDER HOME SWEET HOME",
  "GIFT BAG LARGE 50'S CHRISTMAS",
  "METAL SIGN DROP YOUR PANTS",
  "HEART MIRROR ANTIQUE WHITE",
  "SPACEBOY ROCKET LOLLY MAKERS",
  "SHELF WITH 4 HOOKS HOME SWEET HOME",
  "ENAMEL DINNER PLATE PANTRY",
  "SET 10 CARDS 12 DAYS WRAP  17058",
  "SET 10 CARDS OUT OF ORDER 17216",
  "HOME SWEET HOME HOOK",
  "BATHROOM HOOK",
  "HOME SWEET HOME 3 PEG HANGER",
  "VINTAGE COFFEE GRINDER BOX",
  "PHOTO FRAME LINEN AND LACE LARGE",
  "SET 10 CARDS SCOTTIE DOG 17211",
  "PHOTO FRAME LINEN AND LACE SMALL",
  "RUSTIC MIRROR WITH LACE HEART",
  "PANTRY HOOK BALLOON WHISK",
  "SET 10 XMAS CARDS & BADGES 17070",
  "SET 10 CARDS JINGLE BELLS 16957",
  "CURIO CABINET LINEN AND LACE",
  "WOODLAND BUNNIES LOLLY MAKERS",
  "PANTRY 3 HOOK ROLLING PIN HANGER",
  "PANTRY HOOK SPATULA",
  "3 RAFFIA RIBBONS VINTAGE CHRISTMAS",
  "LAVENDER TOILETTE BOTTLE",
  "HOME SWEET HOME BOTTLE",
  "3 RAFFIA RIBBONS 50'S CHRISTMAS",
  " I LOVE LONDON MINI BACKPACK",
  "DOLLY GIRL MINI BACKPACK",
  "SPACEBOY MINI BACKPACK",
  "EMBOSSED HEART TRINKET BOX",
  "WOODLAND MINI BACKPACK",
  "PAINTED HEART WREATH WITH BELL",
  "CHAMBRE HOOK",
  "SET 10 CARDS RED RIDING HOOD 17214",
  "SET 10 CARDS HATS & STOCKINGS 17081",
  "CHRISTMAS HANGING SNOWFLAKE",
  "PANTRY HOOK TEA STRAINER",
  "SET 6 CARDS SPARKLY REINDEER 17262",
  "SET 10 CARDS MAGICAL TREE 17086",
  "PANTRY CHOPPING BOARD",
  "ACRYLIC HANGING JEWEL,PINK",
  "BLUE CLIMBING HYDRANGA ART FLOWER",
  "LE JARDIN BOTANIQUE CUSHION COVER",
  "FLOWER FAIRY 5 SUMMER DRAW LINERS",
  "SET 10 CARDS DRESSING UP 17077",
  "SET 10 CARDS HANGING BAUBLES 17080",
  "PLAYING CARDS KEEP CALM & CARRY ON",
  "SET 12 COLOURING PENCILS DOILY",
  "SET 12 COLOUR PENCILS SPACEBOY",
  "PLAYING CARDS JUBILEE UNION JACK",
  "SET 36 COLOUR PENCILS SPACEBOY",
  "MINI PLAYING CARDS SPACEBOY",
  "PLAYING CARDS VINTAGE DOILEY",
  "SET 36 COLOUR PENCILS DOILY",
  "SET 12 COLOUR PENCILS DOILY",
  "PACK OF 12 DOILEY TISSUES",
  "VINTAGE DOILY TRAVEL SEWING KIT",
  "SET 12 COLOUR PENCILS LOVE LONDON",
  "SET 36 COLOUR PENCILS LOVE LONDON",
  "EMBROIDERED RIBBON REEL RUBY",
  "EMBROIDERED RIBBON REEL EMILY",
  "EMBROIDERED RIBBON REEL REBECCA",
  "SET 36 COLOURING PENCILS DOILY",
  "SET 12 COLOUR PENCILS DOLLY GIRL",
  "PLAYING CARDS I LOVE LONDON",
  "SET 36 COLOUR PENCILS DOLLY GIRL",
  "EMBROIDERED RIBBON REEL ROSIE",
  "EMBROIDERED RIBBON REEL DAISY",
  "EMBROIDERED RIBBON REEL SALLY",
  "EMBROIDERED RIBBON REEL RACHEL",
  "MINI PLAYING CARDS GYMKHANA",
  "MINI PLAYING CARDS DOLLY GIRL",
  "MINI PLAYING CARDS FUN FAIR",
  "MINI PLAYING CARDS BUFFALO BILL",
  "EMBROIDERED RIBBON REEL SUSIE",
  "SET 10 CARD PERFECT NATIVITY 17089",
  "ROUND CACTUS CANDLE",
  "DOLLY GIRL MINI RUCKSACK",
  "SPACEBOY MINI RUCKSACK",
  "PLAYING CARDS VINTAGE DOILY",
  "LARGE BLACK DIAMANTE HAIRSLIDE",
  "SET 10 CARDS CHRISTMAS ROBIN 17095",
  "PACK OF 12 CHRISTMAS FUN CARDS",
  "SET 10 CARDS SNOWY SNOWDROPS  17100",
  "SET 10 CARDS CHEERFUL ROBIN 17065",
  "EMBROIDERED RIBBON REEL SOPHIE",
  "EMBROIDERED RIBBON REEL CLAIRE",
  "VINTAGE DOILY DELUXE SEWING KIT",
  "SET 10 CARDS ROBIN WATERPUMP  17096",
  "SET 10 CARDS FILIGREE BAUBLE 16961",
  "SMOKEY GREY COLOUR GLASS",
  "SWEETHEART BIRD HOUSE",
  "TUSCAN VILLA DOVECOTE",
  "CARD HOLDER LOVE BIRD SMALL",
  "HEART TRELLISTRIPLE T-LIGHT HOLDER",
  "VINTAGE LEAF CHOPPING BOARD",
  "POPPY FIELDS CHOPPING BOARD",
  "RED APPLES CHOPPING BOARD",
  "SIX DRAWER OFFICE TIDY",
  "VEGETABLE GARDEN CHOPPING BOARD",
  "SET 10 CARDS CHRISTMAS TREE 16955",
  " NINE DRAWER OFFICE TIDY",
  "CARD HOLDER LOVE BIRD LARGE",
  "HORSE & PONY WALL ART",
  "BICYCLE SAFTEY WALL ART",
  "STOP FOR TEA WALL ART",
  "WALL ART CLASSIC PUDDINGS",
  "BUFFALO BILL WALL ART",
  "WALL ART WORK REST AND PLAY",
  "WALL ART LOVES' SECRET",
  "DOG AND BALL WALL ART",
  "DOG LICENCE WALL ART",
  "WALL ART GARDEN HAVEN",
  "70'S ALPHABET WALL ART",
  "SPACEBOY WALL ART",
  "KEEP CALM WALL ART",
  "WALL ART ONLY ONE PERSON",
  "WALL ART VINTAGE HEART",
  "CAT AND BIRD WALL ART",
  "TREASURE AHOY WALL ART",
  "WALL ART BIG LOVE",
  "ANIMALS AND NATURE WALL ART",
  "HANGING  BUTTERFLY T-LIGHT HOLDER",
  "DOLLY GIRL WALL ART",
  "VILLAGE SHOW WALL ART",
  "WALL ART MID CENTURY MODERN",
  "WALL ART THE MAGIC FOREST",
  "I LOVE LONDON WALL ART",
  "WALL ART KEEP CALM",
  "WALL ART BICYCLE SAFTEY",
  "WALL ART BUFFALO BILL",
  "WALL ART VILLAGE SHOW",
  "WALL ART STOP FOR TEA",
  "WALL ART DOG LICENCE",
  "WALL ART SPACEBOY",
  "SET 10 MINI SANTA & SNOWMAN  17087",
  "SET 10 CARDS DINKY TREE 17076",
  "WALL ART I LOVE LONDON",
  "WALL ART 70'S ALPHABET",
  "KEY RING BASEBALL BOOT ASSORTED",
  "WALL ART HORSE & PONY",
  "WALL ART ANIMALS AND NATURE",
  "PINK HORSE SOCK PUPPET KIT",
  "HEART TRELLIS TRIPLE T-LIGHT HOLDER",
  "WALL ART CAT AND BIRD",
  "TUSCAN VILLA FEEDING STATION",
  "KEY RING BASEBALL BOOT UNION JACK",
  "WALL ART BICYCLE SAFETY",
  "VINTAGE  2 METRE FOLDING RULER",
  "WALL ART DOLLY GIRL",
  "SET 10 CARDS 12 DAYS OF XMAS 17059",
  "SET 10 CARDS POINSETTIA 17093",
  "SET 10 CARDS CHRISTMAS HOLLY  17259",
  " I LOVE LONDON MINI RUCKSACK",
  "SET 36 COLOURING PENCILS DOILEY",
  "SET 12 COLOURING PENCILS DOILEY",
  "WOODLAND MINI RUCKSACK",
  "WALL ART DOG AND BALL",
  "WALL ART , LOVES' SECRET",
  "WALL ART,ONLY ONE PERSON",
  "WALL ART ,PUDDINGS",
  "SET 10 MINICARDS CUTE SNOWMAN 17071",
  "TUSCAN VILLA BIRD TABLE",
  "N0 SINGING METAL SIGN",
  "UBO-LIGHT TRIOBASE PURPLE",
  "SILVER 2 STRAND NECKLACE-LEAF CHARM",
  "SILVER M.O.P. ORBIT NECKLACE",
  "GOLD M.O.P. ORBIT NECKLACE",
  "TUSCAN VILLA DOVECOTE BIRD FEEDER",
  "WALL ART , THE MAGIC FOREST",
  "CREAM BUNNY EASTER EGG BASKET",
  "PINK BUNNY EASTER EGG BASKET",
  "BLUE BUNNY EASTER EGG BASKET",
  "WALL ART TREASURE AHOY",
  "S/4 BLACK DISCO PARTITION PANEL",
  "BLACK VINT ART DEC CRYSTAL BRACELET",
  "BOX OF 6 CHRISTMAS CAKE DECORATIONS",
  "HENRIETTA HEN MUG",
  "MILK MAIDS MUG",
  "EGG CUP MILKMAID INGRID",
  "PINK HANGING HEART T-LIGHT HOLDER",
  "EGG CUP HENRIETTA HEN PINK",
  "SWEET HEART CAKE CARRIER",
  "T-LIGHT HOLDER HANGING LOVE BIRD",
  "OVAL  MINI PORTRAIT FRAME",
  "HEART MINI PORTRAIT FRAME",
  "SQUARE MINI PORTRAIT FRAME",
  "PEARLISED IVORY HEART LARGE",
  "SET 10 CARD KRAFT REINDEER 17084",
  "DOLLY CABINET 2 DRAWERS",
  "EGG CUP MILKMAID HELGA",
  "MEDIUM PARLOUR PICTURE FRAME",
  "VINTAGE ZINC WATERING CAN",
  "VINTAGE ZINC WATERING CAN SMALL",
  "LARGE PARLOUR PICTURE FRAME",
  "SMALL PARLOUR PICTURE FRAME",
  "EGG CUP HENRIETTA HEN CREAM",
  "EGG CUP MILKMAID HEIDI",
  "VINTAGE ZINC PLANTER",
  "WIRE EGG BASKET",
  "PEARLISED IVORY HEART SMALL",
  "DOLLY CABINET 3 DRAWERS",
  "SNACK TRAY I LOVE LONDON",
  "DECROTIVEVINTAGE COFFEE GRINDER BOX",
  "LANDMARK FRAME LONDON BRIDGE",
  "LANDMARK FRAME COVENT GARDEN",
  "LANDMARK FRAME OXFORD STREET",
  "LANDMARK FRAME BAKER STREET",
  "LANDMARK FRAME NOTTING HILL",
  "MINI LIGHTS WOODLAND MUSHROOMS",
  "LANDMARK FRAME CAMDEN TOWN",
  "GARLAND, VINTAGE BELLS",
  "VINTAGE JINGLE BELLS HEART",
  "VINTAGE JINGLE BELLS WREATH",
  "WOODLAND LARGE BLUE FELT HEART",
  "WOODLAND LARGE PINK FELT HEART",
  "WOODLAND LARGE RED FELT HEART",
  "ANTIQUE HEART SHELF UNIT",
  "WOODLAND SMALL RED FELT HEART",
  "SWEETHEART WALL TIDY",
  "ROCOCO WALL MIRROR WHITE",
  "BOTANICAL GARDENS WALL CLOCK",
  "VINTAGE BELLS GARLAND",
  "ROCOCO WALL MIROR",
  "TRADITIONAL PICK UP STICKS GAME",
  "SET OF 3 MINI HANGING PORTRAITS",
  "TRADITIONAL NAUGHTS & CROSSES",
  "TRADTIONAL ALPHABET STAMP SET",
  "SET 4 PICNIC CUTLERY BLUEBERRY",
  "THREE MINI HANGING FRAMES",
  "WOODLAND SMALL BLUE FELT HEART",
  "SET 10 CARDS WISHING TREE 17116",
  "STRAWBERRY CERAMIC TRINKET POT",
  "VINTAGE DOILY JUMBO BAG RED",
  "LUNCH BAG PAISLEY PARK",
  "JUMBO BAG PAISLEY PARK",
  "UBO-LIGHT TRIOBASE BLUE",
  "SET OF 36 VINTAGE CHRISTMAS DOILIES",
  "SET OF 36 SPACEBOY PAPER DOILIES",
  "SET OF 36 DOLLY GIRL PAPER DOILIES",
  "DECORATIVE VINTAGE COFFEE  BOX",
  "SET OF 36 PANTRY PAPER DOILIES",
  "SET 4 PICNIC CUTLERY FONDANT",
  "WOODLAND SMALL PINK FELT HEART",
  "SET 10 CARDS PRINTED GRAPHIC 17219",
  "SET 10 CHRISTMAS CARDS HOHOHO 16956",
  "SET 10 CARD SNOWMAN 16965",
  "SILVER RECORD COVER FRAME",
  "CLASSIC CHROME BICYCLE BELL",
  "SET 4 PICNIC CUTLERY CHERRY",
  "SET OF 3 PANTRY WOODEN SPOONS",
  "PANTRY KITCHEN THERMOMETER",
  "SET 10 CARDS TRIANGLE ICONS  17220",
  "SET 10 CARDS WORLD CHILDREN 17067",
  "SET 10 CARDS CHRISTMAS BAUBLE 16954",
  "LIGHT DECORATION BATTERY OPERATED",
  "KEEP CALM BIRTHDAY WRAP",
  "RUBY GLASS CLUSTER NECKLACE",
  "WRAP KEEP CALM BIRTHDAY",
  "SET 10 CARDS RUDOLPHS NOSE 17097",
  "LUNCH BAG RED VINTAGE DOILY",
  "BLACK SIL'T SQU CANDLE PLATE",
  "ANT SILVER TURQUOISE BOUDICCA RING",
  "PINK POLKADOT PLATE",
  "ST GEORGE SET OF 10 PARTY LIGHTS",
  "WRAP A PRETTY THANK YOU",
  "CLASSIC CROME BICYCLE BELL",
  "DOILY THANK YOU CARD",
  "A PRETTY THANK YOU CARD",
  "SET 10 CARDS JINGLE BELLS 17217",
  "TUSCAN VILLA BIRD FEEDER",
  "PAPER BUNTING VINTAGE PARTY",
  "PAPER BUNTING PAISLEY PARK",
  "SET 10 CARDS DAVID'S MADONNA 17074",
  "SET 10 CARDS XMAS GRAPHIC  17218",
  "LARGE PARLOUR FRAME",
  "MEDIUM PARLOUR FRAME",
  "SMALL PARLOUR FRAME",
  "SET 10 CARDS 3 WISE MEN 17107",
  "FLOWER SHOP DESIGN MUG",
  "ROSE FLOWER CANDLE+INCENSE 16X16CM",
  "WHITE CHRISTMAS TREE 60CM",
  "PAISLEY PARK CARD",
  "PACK 3 BOXES CHRISTMAS PANETTONE",
  "PACK OF 6 PANETTONE GIFT BOXES",
  "PACK 3 BOXES BIRD PANETTONE",
  "COLOURED GLASS STAR T-LIGHT HOLDER",
  "SET 10 CARDS DECK THE HALLS 16960",
  "12 HANGING EGGS HAND PAINTED",
  "SET OF 6 EASTER RAINBOW CHICKS",
  "DUSTY PINK CHRISTMAS TREE 60CM",
  "IVORY RETRO KITCHEN WALL CLOCK",
  "SET 10 CARD CHRISTMAS STAMPS 16963",
  "WHITE MOROCCAN METAL LANTERN",
  "CAT WITH SUNGLASSES BLANK CARD",
  "BLUE RETRO KITCHEN WALL CLOCK",
  "RED RETRO KITCHEN WALL CLOCK",
  "PURPLE FINE BEAD NECKLACE W TASSEL",
  "HAND PAINTED HANGING EASTER EGG",
  "PAINT YOUR OWN EGGS IN CRATE",
  "BICYCLE PUNCTURE REPAIR KIT",
  "CLASSIC BICYCLE CLIPS",
  "CROCHET LILAC/RED BEAR KEYRING",
  "SILVER AND BLACK ORBIT NECKLACE",
  "LARGE HEART FLOWERS HOOK",
  "GIN AND TONIC DIET METAL SIGN",
  "SNACK TRAY RED GINGHAM",
  "SNACK TRAY HAPPY FOREST",
  "SNACK TRAY PAISLEY PARK",
  "SET OF 6 RIBBONS COUNTRY STYLE",
  "SNACK TRAY RED VINTAGE DOILY",
  "SET OF 6 RIBBONS PERFECTLY PRETTY",
  "SET OF 6 RIBBONS PARTY",
  "SET 10 CARDS SNOWY ROBIN 17099",
  "SET 10 CARDS SWIRLY XMAS TREE 17104",
  "LETTER \"U\" BLING KEY RING",
  "CREAM HANGING HEART T-LIGHT HOLDER",
  "PAPER CRAFT , LITTLE BIRDIE"
];

function ProductDropdownPortal({ open, anchorRef, options, onSelect, highlightedIndex }) {
  const [pos, setPos] = useState({ top: 0, left: 0, width: 0 });

  useLayoutEffect(() => {
    if (!open || !anchorRef.current) return;
    const rect = anchorRef.current.getBoundingClientRect();
    setPos({
      top: rect.bottom + window.scrollY + 4,
      left: rect.left + window.scrollX,
      width: rect.width
    });
  }, [open, anchorRef, options]);

  if (!open || options.length === 0) return null;

  return createPortal(
    <div
      style={{
        position: 'absolute',
        top: pos.top,
        left: pos.left,
        width: pos.width,
        zIndex: 99999
      }}
    >
      <ul className="max-h-60 overflow-y-auto bg-white border border-gray-200 rounded-md shadow-lg">
        {options.map((p, idx) => (
          <li
            key={`${p}-${idx}`}
            className={`px-4 py-2 cursor-pointer text-sm ${
              idx === highlightedIndex ? 'bg-blue-50 text-blue-700 font-medium' : 'hover:bg-gray-100 text-gray-800'
            }`}
            onMouseDown={(e) => {
              e.preventDefault();
              onSelect(p);
            }}
          >
            {p}
          </li>
        ))}
      </ul>
    </div>,
    document.body
  );
}

function PredictionPage() {
  const [formData, setFormData] = useState({
    unit_price: 2.55,
    customer_id: '',
    country: 'United Kingdom',
    order_date: new Date().toISOString().split('T')[0],
    order_time: '23:12',
    product: ''
  });

  const [products, setProducts] = useState([]);
  const [productSearch, setProductSearch] = useState('');
  const [showProductDropdown, setShowProductDropdown] = useState(false);
  const [highlightedIndex, setHighlightedIndex] = useState(-1);
  const dropdownRef = useRef(null);
  const listRef = useRef(null);

  // ─── FETCH PRODUCTS FROM API (fallback to static list) ───
  useEffect(() => {
    fetch(`${API_BASE}/products`)
      .then(res => res.json())
      .then(data => {
        if (data.success) {
          const apiProducts = Array.isArray(data.products) ? data.products : [];
          setProducts(apiProducts.length > 0 ? apiProducts : ALL_PRODUCTS);
        } else {
          setProducts(ALL_PRODUCTS);
        }
      })
      .catch(err => {
        console.error("Error fetching products:", err);
        setProducts(ALL_PRODUCTS);
      });
  }, []);

  // ─── CLICK OUTSIDE TO CLOSE ───
  useEffect(() => {
    const handleClickOutside = (event) => {
      if (dropdownRef.current && !dropdownRef.current.contains(event.target)) {
        setShowProductDropdown(false);
        setHighlightedIndex(-1);
      }
    };
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, []);

  // ─── KEYBOARD NAVIGATION ───
  const handleProductKeyDown = (e) => {
    if (!showProductDropdown) return;

    switch (e.key) {
      case 'ArrowDown':
        e.preventDefault();
        setHighlightedIndex(prev => {
          const next = prev < filteredProducts.length - 1 ? prev + 1 : 0;
          // Auto-scroll to highlighted item
          setTimeout(() => {
            const el = listRef.current?.children[next];
            el?.scrollIntoView({ block: 'nearest' });
          }, 0);
          return next;
        });
        break;
      case 'ArrowUp':
        e.preventDefault();
        setHighlightedIndex(prev => {
          const next = prev > 0 ? prev - 1 : filteredProducts.length - 1;
          setTimeout(() => {
            const el = listRef.current?.children[next];
            el?.scrollIntoView({ block: 'nearest' });
          }, 0);
          return next;
        });
        break;
      case 'Enter':
        e.preventDefault();
        if (highlightedIndex >= 0 && highlightedIndex < filteredProducts.length) {
          handleProductSelect(filteredProducts[highlightedIndex]);
        }
        break;
      case 'Escape':
        setShowProductDropdown(false);
        setHighlightedIndex(-1);
        break;
    }
  };

  const handleProductSelect = (productName) => {
    setProductSearch(productName);
    setFormData(prev => ({ ...prev, product: productName }));
    setShowProductDropdown(false);
    setHighlightedIndex(-1);
  };

  const filteredProducts = products
    .filter(p => String(p).toLowerCase().includes(productSearch.toLowerCase()))
    .slice(0, 50);

  const [history, setHistory] = useState([]);
  const [latestPrediction, setLatestPrediction] = useState(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState(null);
  const [predictionCount, setPredictionCount] = useState(0);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const handlePredict = useCallback(async (e) => {
    e.preventDefault();
    setIsLoading(true);
    setError(null);

    try {
      const payload = {
        ...formData,
        product: productSearch,
        unit_price: parseFloat(formData.unit_price) || 0
      };

      const res = await fetch(`${API_BASE}/predict`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });

      const data = await res.json();

      if (!data.success) {
        throw new Error(data.error || 'Prediction failed');
      }

      const newPrediction = {
        time: new Date().toLocaleTimeString('en-US', {
          hour12: false,
          hour: '2-digit',
          minute: '2-digit',
          second: '2-digit'
        }),
        predicted: data.predicted_quantity,
        timestamp: Date.now()
      };

      setHistory(prev => {
        const updated = [...prev, newPrediction];
        return updated.slice(-50);
      });

      setLatestPrediction({
        ...newPrediction,
        predicted_quantity: data.predicted_quantity,
        scenarios: data.scenarios,
        index: predictionCount + 1
      });

      setPredictionCount(c => c + 1);
    } catch (err) {
      setError(err.message);
    } finally {
      setIsLoading(false);
    }
  }, [formData, productSearch, predictionCount]);

  const handleReset = () => {
    setHistory([]);
    setLatestPrediction(null);
    setPredictionCount(0);
    setError(null);
    setProductSearch('');
    setFormData(prev => ({ ...prev, product: '' }));
  };

  const handleSimulate = () => {
    const mockPredictions = [
      { time: '21:00:00', predicted: 12 },
      { time: '21:05:00', predicted: 18 },
      { time: '21:10:00', predicted: 15 },
      { time: '21:15:00', predicted: 22 },
      { time: '21:20:00', predicted: 19 },
    ];

    mockPredictions.forEach((p, i) => {
      setTimeout(() => {
        setHistory(prev => [...prev.slice(-49), { ...p, timestamp: Date.now() + i }]);
        setLatestPrediction({
          ...p,
          predicted_quantity: p.predicted,
          index: predictionCount + i + 1
        });
        setPredictionCount(c => c + 1);
      }, i * 300);
    });
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-gray-900">Demand Forecasting</h1>
        <p className="text-gray-500 mt-1">Predict retail demand with ML-powered insights</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        <div className="lg:col-span-4">
          <div className="card sticky top-24 overflow-visible">
            <div className="mb-6">
              <h2 className="text-xl font-bold text-gray-900 mb-1" style={{ color: '#0d324d', fontFamily: 'serif' }}>
                New Order Line
              </h2>
              <p className="text-sm text-gray-500">
                Enter an order line to forecast how many units will be bought.
              </p>
            </div>

            <form onSubmit={handlePredict} className="space-y-4 overflow-visible">
              {/* ─── SCROLLING PRODUCT SELECTOR ─── */}
              <div className="relative" ref={dropdownRef}>
                <label className="flex items-center gap-2 font-medium text-gray-700 mb-1.5 uppercase tracking-wider text-xs">
                  PRODUCT
                </label>

                <div className="relative">
                  <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                    <Search className="h-4 w-4 text-gray-400" />
                  </div>
                  <input
                    type="text"
                    value={productSearch}
                    onChange={(e) => {
                      setProductSearch(e.target.value);
                      setShowProductDropdown(true);
                      setHighlightedIndex(-1);
                    }}
                    onFocus={() => setShowProductDropdown(true)}
                    onClick={() => setShowProductDropdown(true)}
                    onKeyDown={handleProductKeyDown}
                    className="input-field pl-10 pr-10"
                    placeholder="Search or scroll to select product..."
                    required
                  />
                  {/* Clear button */}
                  {productSearch && (
                    <button
                      type="button"
                      onClick={() => {
                        setProductSearch('');
                        setFormData(prev => ({ ...prev, product: '' }));
                        setShowProductDropdown(true);
                      }}
                      className="absolute inset-y-0 right-0 pr-3 flex items-center text-gray-400 hover:text-gray-600"
                    >
                      <X className="h-4 w-4" />
                    </button>
                  )}
                  {/* Dropdown arrow */}
                  <button
                    type="button"
                    onClick={() => {
                      setShowProductDropdown(!showProductDropdown);
                      if (!showProductDropdown) setHighlightedIndex(-1);
                    }}
                    className="absolute inset-y-0 right-0 pr-3 flex items-center text-gray-400 hover:text-gray-600"
                    style={{ right: productSearch ? '28px' : '0' }}
                  >
                    <ChevronDown className={`h-4 w-4 transition-transform ${showProductDropdown ? 'rotate-180' : ''}`} />
                  </button>
                </div>

                {/* ─── SCROLLING DROPDOWN WITH KEYBOARD NAV ─── */}
                {showProductDropdown && filteredProducts.length > 0 && (
                  <div
                    ref={listRef}
                    className="absolute z-50 w-full mt-1 max-h-60 overflow-y-auto bg-white border border-gray-200 rounded-md shadow-lg"
                  >
                    {filteredProducts.map((p, idx) => (
                      <div
                        key={`${p}-${idx}`}
                        className={`px-4 py-2.5 cursor-pointer text-sm transition-colors ${
                          idx === highlightedIndex
                            ? 'bg-blue-50 text-blue-700 font-medium border-l-2 border-blue-500'
                            : 'text-gray-700 hover:bg-gray-50 hover:text-gray-900'
                        }`}
                        onMouseEnter={() => setHighlightedIndex(idx)}
                        onMouseDown={(e) => {
                          e.preventDefault();
                          handleProductSelect(p);
                        }}
                      >
                        <div className="flex items-center gap-2">
                          {idx === highlightedIndex && (
                            <span className="w-1.5 h-1.5 rounded-full bg-blue-500" />
                          )}
                          <span className="truncate">{p}</span>
                        </div>
                      </div>
                    ))}
                    {filteredProducts.length === 50 && productSearch && (
                      <div className="px-4 py-2 text-xs text-gray-400 text-center border-t border-gray-100">
                        Showing top 50 matches — type more to refine
                      </div>
                    )}
                  </div>
                )}

                {showProductDropdown && filteredProducts.length === 0 && (
                  <div className="absolute z-50 w-full mt-1 bg-white border border-gray-200 rounded-md shadow-lg px-4 py-3 text-sm text-gray-500 text-center">
                    No products found
                  </div>
                )}
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="flex items-center gap-2 font-medium text-gray-700 mb-1.5 uppercase tracking-wider text-xs">
                    UNIT PRICE (£)
                  </label>
                  <input
                    type="number"
                    name="unit_price"
                    step="0.01"
                    min="0"
                    value={formData.unit_price}
                    onChange={handleChange}
                    className="input-field"
                    required
                  />
                </div>
                <div>
                  <label className="flex items-center gap-2 font-medium text-gray-700 mb-1.5 uppercase tracking-wider text-xs">
                    CUSTOMER ID
                  </label>
                  <input
                    type="text"
                    name="customer_id"
                    value={formData.customer_id}
                    onChange={handleChange}
                    className="input-field"
                    placeholder="17850 (optional)"
                  />
                </div>
              </div>

              <div>
                <label className="flex items-center gap-2 font-medium text-gray-700 mb-1.5 uppercase tracking-wider text-xs">
                  COUNTRY
                </label>
                <div className="relative">
                  <select
                    name="country"
                    value={formData.country}
                    onChange={handleChange}
                    className="input-field appearance-none"
                    required
                  >
                    {COUNTRIES.map(c => (
                      <option key={c} value={c}>{c}</option>
                    ))}
                  </select>
                </div>
              </div>

              <div>
                <label className="flex items-center gap-2 font-medium text-gray-700 mb-1.5 uppercase tracking-wider text-xs">
                  ORDER DATE
                </label>
                <div>
                  <input
                    type="date"
                    name="order_date"
                    value={formData.order_date}
                    onChange={handleChange}
                    className="input-field"
                    required
                  />
                </div>
              </div>

              {error && (
                <div className="flex items-center gap-2 p-3 bg-rose-50 border border-rose-200 rounded-lg">
                  <AlertCircle className="w-4 h-4 text-rose-500 flex-shrink-0" />
                  <p className="text-sm text-rose-700">{error}</p>
                </div>
              )}

              <button
                type="submit"
                disabled={isLoading}
                className="w-full flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed text-white font-medium py-2.5 px-4 rounded-lg transition-colors bg-blue-600 hover:bg-blue-700"
              >
                {isLoading ? (
                  <>
                    <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                    Predicting...
                  </>
                ) : (
                  <>Forecast quantity</>
                )}
              </button>

              <div className="flex gap-2">
                <button
                  type="button"
                  onClick={handleSimulate}
                  className="flex-1 py-2 px-4 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg text-sm font-medium transition-colors"
                >
                  Simulate Data
                </button>
                <button
                  type="button"
                  onClick={handleReset}
                  className="flex-1 py-2 px-4 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg text-sm font-medium transition-colors flex items-center justify-center gap-1"
                >
                  <RotateCcw className="w-3.5 h-3.5" />
                  Reset
                </button>
              </div>
            </form>
          </div>
        </div>

        <div className="lg:col-span-8 space-y-6">
          <PredictionCard prediction={latestPrediction} isLoading={isLoading} />

          <PredictionInsights prediction={latestPrediction} />

          <div className="card">
            <PredictionChart data={history} showLastN={10} />
          </div>

          {history.length > 0 && (
            <div className="card">
              <div className="flex items-center gap-2 mb-4">
                <History className="w-5 h-5 text-primary-600" />
                <h3 className="text-lg font-semibold text-gray-900">Prediction Ledger</h3>
                <span className="ml-auto text-xs text-gray-400">
                  {history.length} total predictions
                </span>
              </div>
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="border-b border-gray-100">
                      <th className="text-left py-2 px-3 text-xs font-semibold text-gray-500 uppercase">#</th>
                      <th className="text-left py-2 px-3 text-xs font-semibold text-gray-500 uppercase">Time</th>
                      <th className="text-right py-2 px-3 text-xs font-semibold text-gray-500 uppercase">Predicted Qty</th>
                      <th className="text-right py-2 px-3 text-xs font-semibold text-gray-500 uppercase">Change</th>
                    </tr>
                  </thead>
                  <tbody>
                    {history.slice().reverse().slice(0, 10).map((item, idx) => {
                      const prev = history[history.length - 1 - idx - 1];
                      const change = prev ? item.predicted - prev.predicted : 0;
                      return (
                        <tr key={item.timestamp} className="border-b border-gray-50 hover:bg-gray-50 transition-colors">
                          <td className="py-2.5 px-3 text-gray-400">{history.length - idx}</td>
                          <td className="py-2.5 px-3 font-mono text-gray-600">{item.time}</td>
                          <td className="py-2.5 px-3 text-right font-semibold text-primary-700">
                            {item.predicted}
                          </td>
                          <td className="py-2.5 px-3 text-right">
                            {change !== 0 && (
                              <span className={`text-xs font-medium px-2 py-0.5 rounded-full ${
                                change > 0 ? 'bg-emerald-50 text-emerald-700' : 'bg-rose-50 text-rose-700'
                              }`}>
                                {change > 0 ? '+' : ''}{change.toFixed(1)}
                              </span>
                            )}
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

export default PredictionPage;